- name: Authentication API
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Log in to website
      uri:
        url: https://sandboxdnac.cisco.com/dna/system/api/v1/auth/token
        method: POST
        body: {}
        headers:
          Content-Type: application/json
          Authorization: "Basic ZGV2bmV0dXNlcjpDaXNjbzEyMyE="
        validate_certs: no
      register: login_response

    - name: Add user API
      uri:
        url: https://sandboxdnac.cisco.com/dna/system/api/v1/user
        method: POST
        body_format: json
        body: >
          {
            "firstName": "ram",
            "lastName": "puvvada",
            "username": "puvvadaj",
            "password": "Cisco@123",
            "email": "ram@gmail.com",
            "roleList": [
              "OBSERVER-ROLE"
            ]
          }
        headers:
          Content-Type: application/json
          X-Auth-Token: "{{ login_response.json.Token }}"
        validate_certs: no

