- name: Authentication API
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Log in to website
      uri:
        url: https://sandboxdnac.cisco.com/dna/system/api/v1/auth/token
        method: POST
        body: {}
        headers:
          Content-Type: application/json
          Authorization: "Basic ZGV2bmV0dXNlcjpDaXNjbzEyMyE="
        validate_certs: no
      register: login_response

    - name: Get users API
      uri:
        url: https://sandboxdnac.cisco.com/dna/system/api/v1/user?invokeSource=external
        method: GET
        headers:
          X-Auth-Token: "{{ login_response.json.Token }}"
          Content-Type: application/json
        validate_certs: no
      register: users_response

    - name: Display users
      debug:
        var: users_response.json
