---
- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get Network Device by id
      cisco.dnac.network_device_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        id: 5f03d9a9-33df-450e-b0c3-6bcb5f721688
      register: network_device_result

    - name: Get Count of Network Device
      cisco.dnac.network_device_count_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
      register: device_count

    - name: Get all sites info
      cisco.dnac.site_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
      register: result

    - name: Displaying  all sites info 
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Displaying network_device Using Id 
      ansible.builtin.debug:
        msg: "{{ network_device_result }}"

    - name: Displaying Total Count Of Devices 
      ansible.builtin.debug:
        msg: "{{ device_count }}"


